- WEB:
    Driver: $rootpath/Drivers/chromedriver
    TestDataPath: $rootpath/Resource/$appname/test_data.yaml
    DomElement: $rootpath/Resource/$appname/dom_element.yaml
    POM_business_path: $rootpath/Components/Business/$appname

- Logger:
      version: 1
      formatters:
          simple:
              format: '%(asctime)s|%(levelname)-6s|%(filename)-12s:Line%(lineno)d|%(message)s'
              datefmt: '%Y-%m-%d %H:%M:%S'
      handlers:
          fileHandler:
              class: logging.handlers.TimedRotatingFileHandler
              level: DEBUG
              formatter: simple
              filename:
              when: midnight
              interval: 1
              backupCount: 1
              encoding: utf-8
          consoleHandler:
              class: logging.StreamHandler
              level: INFO
              formatter: simple
              stream: ext://sys.stderr
      loggers:
          applog:
              level: DEBUG
              handlers: [ consoleHandler, fileHandler ]
              propagate: no
      root:
          level: DEBUG
          handlers: [ consoleHandler, fileHandler ]

- ENV:
    "QA":
#      url: http://172.20.4.217:3002/login
      url: https://eyeguide-test.essexlg.com:6443/
      userName: xingyang.han@essexlg.com
      passWord: 1qaz@WSX3edc
#      userName: essexa2021@163.com
#      passWord: Essex@709
      project_name: "AutomationTest"
      dashboard_name: "AutomationDashboard"
    ADG:
        url: https://eyeguide-designer.essexlg.com:6443
        userName: xingyang.han@essexlg.com
        passWord: "#BZNfdiori7"
        project_name: "AutomationTest"
        dashboard_name: "AutomationDashboard"
    Staging:
      url: https://eyeguide-staging.essexlg.com:6443/
      userName: xingyang.han@essexlg.com
      passWord: 1qaz@WSX3edc
      project_name: "AutomationTest"
      dashboard_name: "AutomationDashboard"
    Execute:
      url:
      userName:
      passWord:
      project_name:
      dashboard_name: