- API:
    Domain: http://localhost:3000/
    ReportPath: --html=./Report/test_report_api/$apiname
#    ConfigPath: ../../../Resource/$apiname/config.yaml
    ConfigPath: ./Resource/$apiname/config.yaml
#    TestDataPath: ../../../Resource/$apiname/test_data.yaml
    TestDataPath: ./Resource/$apiname/test_data.yaml

- WEB:
    Driver: ./Drivers/chromedriver.exe
    Driver-m1: ./Drivers/chromedriver_M1

- Logger:
      version: 1
      formatters:
          simple:
              format: '%(asctime)s|%(levelname)-6s|%(filename)-12s:Line%(lineno)d|%(message)s'
              datefmt: '%Y-%m-%d %H:%M:%S'
      handlers:
          fileHandler:
              class: logging.handlers.TimedRotatingFileHandler
              level: DEBUG
              formatter: simple
              filename: TestDemoApi
              when: midnight
              interval: 1
              backupCount: 1
          consoleHandler:
              class: logging.StreamHandler
              level: DEBUG
              formatter: simple
              stream: ext://sys.stderr
      loggers:
          applog:
              level: INFO
              handlers: [ consoleHandler, fileHandler ]
              propagate: no
      root:
          level: DEBUG
          handlers: [ consoleHandler, fileHandler ]