- API:
    Domain: http://localhost:3000/
    ReportPath: --html= $rootpath/Report/test_report_api/$apiname
    ConfigPath: /Resource/$apiname/config.yaml
    TestDataPath: /Resource/$apiname/test_data.yaml

- WEB:
    Driver: $rootpath/Drivers/chromedriver.exe
    Driver-m1: $rootpath/Drivers/chromedriver_M1
    ReportPath: --html= $rootpath/Report/test_report_web/$appname
    ConfigPath: $rootpath/Resource/$appname/config.yaml
    TestDataPath: $rootpath/Resource/$appname/test_data.yaml
    DomElement: $rootpath/Resource/$appname/Dom_Element.yaml
    POM_business_path: $rootpath/POM/Business/$appname

- Logger:
      version: 1
      formatters:
          simple:
              format: '%(asctime)s|%(levelname)-6s|%(filename)-12s:Line%(lineno)d|%(message)s'
              datefmt: '%Y-%m-%d %H:%M:%S'
      handlers:
          fileHandler:
              class: logging.handlers.TimedRotatingFileHandler
              level: DEBUG
              formatter: simple
              filename: TestDemoApi
              when: midnight
              interval: 1
              backupCount: 1
              encoding: utf-8
          consoleHandler:
              class: logging.StreamHandler
              level: DEBUG
              formatter: simple
              stream: ext://sys.stderr
      loggers:
          applog:
              level: INFO
              handlers: [ consoleHandler, fileHandler ]
              propagate: no
      root:
          level: DEBUG
          handlers: [ consoleHandler, fileHandler ]